### PR TITLE
update plugin version

### PR DESCRIPTION
**Pull request by ryota0624**
- rebase gatling/gatling-sbt-plugin-demo/master
- change gatling grpc plugin version
- change gatling bundle version

### CODE REVIEW

**Comment by phiSgr** [comment]
Sorry for the late reply. I didn't see this PR.

Could you put your changes as edits to my commits? (If you use command line, it is `git rebase -i ...`, then `e` the commits.)
So that every commit is a self-containing step of setting up a gRPC load test?
(See how f1789373aaf6d0719759365e041fea4cc69f593f and eaa16bbb9442dc7595fb240027c6f5f11186c4c0 are different).

BTW have you ran the test? I think the first separator in `"com.github.phisgr" %% "gatling-grpc" % "0.11.0" % "test,it"` should be `%` instead of `%%`.

**Comment by ryota0624** [comment]
> Could you put your changes as edits to my commits? (If you use command line, it is git rebase -i ..., then e the commits.)
So that every commit is a self-containing step of setting up a gRPC load test?

ok. I'll try it later

> BTW have you ran the test? I think the first separator in "com.github.phisgr" %% "gatling-grpc" % "0.11.0" % "test,it" should be % instead of %%.

yes! you are correct!
sorry, tests was incorrectly passed only in my environment. 
(Because the one for scala 2.13 of that library remained in my local .ivy2)

**Comment by pluttrell** [comment]
Hey @ryota0624... Wondering if you might be able to complete these changes. Would love to get this merged.

**Comment by ryota0624** [comment]
@pluttrell thanks, mention!
And sorry for leaving it so long.

I cant deal this PR now, so this PR will be CLOSED. sorry!

**Pull request closed without merging**
